export const booksMock = [
  {
    id: "1",
    title: "Il Nome della Rosa",
    author: "Umberto Eco",
    pages: 503,
    genre: "Giallo Storico",
    cover_url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    status: "READ", 
    start_date: "2026-01-10",
    end_date: "2026-01-28",
    rating: 5,
    review_text: "Un capolavoro assoluto della letteratura italiana. Intricato, colto e avvincente.",
    format: "PAPERBACK",
    binding: "Copertina Flessibile",
    is_library: false,
    return_date: null
  },
  {
    id: "2",
    title: "Dune",
    author: "Frank Herbert",
    pages: 688,
    genre: "Fantascienza",
    cover_url: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    status: "OWNED",
    start_date: "2026-02-15",
    end_date: null,
    rating: null,
    review_text: "",
    format: "HARDCOVER",
    binding: "Copertina Rigida",
    is_library: true,
    return_date: "2026-03-15"
  },
  {
    id: "3",
    title: "1984",
    author: "George Orwell",
    pages: 328,
    genre: "Dystopian",
    cover_url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    status: "READ",
    start_date: "2026-02-15",
    end_date: "2026-04-28",
    rating: 5,
    review_text: "Best book of my life",
    format: "HARDCOVER",
    binding: "Copertina Rigida",
    is_library: true,
    return_date: "2026-03-15"
  },
  {
    id: "4",
    title: "L'Ombra del Vento",
    author: "Carlos Ruiz Zafón",
    pages: 526,
    genre: "Mistero",
    cover_url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80",
    status: "WISHLIST",
    start_date: null,
    end_date: null,
    rating: null,
    review_text: null,
    format: null,
    binding: null,
    is_library: false,
    return_date: null
  },
  {
    id: "5",
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    pages: 158,
    genre: "Dystopian",
    cover_url: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=80",
    status: "READ",
    start_date: "2026-05-01",
    end_date: "2026-05-12",
    rating: 4,
    review_text: "Visionario e tristemente attuale. Una riflessione potente sul valore della lettura.",
    format: "PAPERBACK",
    binding: "Copertina Flessibile",
    is_library: false,
    return_date: null
  },
  {
    id: "6",
    title: "Guida Galattica per gli Autostoppisti",
    author: "Douglas Adams",
    pages: 208,
    genre: "Fantascienza Humor",
    cover_url: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    status: "OWNED",
    start_date: null,
    end_date: null,
    rating: null,
    review_text: "",
    format: "KINDLE",
    binding: "Digitale",
    is_library: false,
    return_date: null
  },
  {
    id: "7",
    title: "Il Signore degli Anelli",
    author: "J.R.R. Tolkien",
    pages: 1200,
    genre: "Fantasy",
    cover_url: "https://images.unsplash.com/photo-1463320726281-696a485928c7?auto=format&fit=crop&w=600&q=80",
    status: "OWNED",
    start_date: "2026-06-01",
    end_date: null,
    rating: null,
    review_text: "",
    format: "HARDCOVER",
    binding: "Copertina Rigida",
    is_library: true,
    return_date: "2026-09-30"
  },
  {
    id: "8",
    title: "Neuromante",
    author: "William Gibson",
    pages: 271,
    genre: "Cyberpunk",
    cover_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80",
    status: "WISHLIST",
    start_date: null,
    end_date: null,
    rating: null,
    review_text: null,
    format: null,
    binding: null,
    is_library: false,
    return_date: null
  },
  {
    id: "9",
    title: "Il Problema dei Tre Corpi",
    author: "Cixin Liu",
    pages: 400,
    genre: "Fantascienza",
    cover_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    status: "READ",
    start_date: "2026-03-01",
    end_date: "2026-03-20",
    rating: 5,
    review_text: "Concetti scientifici incredibili. Un approccio originale al primo contatto alieno.",
    format: "HARDCOVER",
    binding: "Copertina Rigida",
    is_library: false,
    return_date: null
  },
  {
    id: "10",
    title: "L'Isola del Tesoro",
    author: "Robert Louis Stevenson",
    pages: 240,
    genre: "Avventura",
    cover_url: "https://images.unsplash.com/photo-1509021436468-d510300f28b4?auto=format&fit=crop&w=600&q=80",
    status: "OWNED",
    start_date: null,
    end_date: null,
    rating: null,
    review_text: "",
    format: "PAPERBACK",
    binding: "Copertina Flessibile",
    is_library: true,
    return_date: "2026-09-20"
  },
  {
    id: "11",
    title: "Cent'anni di Solitudine",
    author: "Gabriel García Márquez",
    pages: 417,
    genre: "Realismo Magico",
    cover_url: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=600&q=80",
    status: "READ",
    start_date: "2026-04-01",
    end_date: "2026-04-22",
    rating: 5,
    review_text: "Un viaggio ipnotico nella storia della famiglia Buendía. Stile unico.",
    format: "PAPERBACK",
    binding: "Copertina Flessibile",
    is_library: false,
    return_date: null
  },
  {
    id: "12",
    title: "Sapiens: Da animali a dèi",
    author: "Yuval Noah Harari",
    pages: 540,
    genre: "Saggistica",
    cover_url: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80",
    status: "OWNED",
    start_date: "2026-07-10",
    end_date: null,
    rating: null,
    review_text: "",
    format: "HARDCOVER",
    binding: "Copertina Rigida",
    is_library: true,
    return_date: "2026-10-10"
  },
  {
    id: "13",
    title: "L'Aleph",
    author: "Jorge Luis Borges",
    pages: 180,
    genre: "Racconti",
    cover_url: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80",
    status: "WISHLIST",
    start_date: null,
    end_date: null,
    rating: null,
    review_text: null,
    format: null,
    binding: null,
    is_library: false,
    return_date: null
  },
  {
    id: "14",
    title: "Il Grande Gatsby",
    author: "F. Scott Fitzgerald",
    pages: 180,
    genre: "Classico",
    cover_url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    status: "READ",
    start_date: "2026-01-02",
    end_date: "2026-01-08",
    rating: 4,
    review_text: "Elegante e malinconico. La rappresentazione perfetta del sogno americano.",
    format: "PAPERBACK",
    binding: "Copertina Flessibile",
    is_library: false,
    return_date: null
  },
  {
    id: "15",
    title: "Klara e il Sole",
    author: "Kazuo Ishiguro",
    pages: 288,
    genre: "Fantascienza",
    cover_url: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=600&q=80",
    status: "OWNED",
    start_date: null,
    end_date: null,
    rating: null,
    review_text: "",
    format: "KINDLE",
    binding: "Digitale",
    is_library: false,
    return_date: null
  },
  {
    id: "16",
    title: "Doppia Trama",
    author: "Agatha Christie",
    pages: 220,
    genre: "Giallo",
    cover_url: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=600&q=80",
    status: "READ",
    start_date: "2026-05-15",
    end_date: "2026-05-18",
    rating: 4,
    review_text: "Classico intreccio alla Poirot, sempre scorrevole.",
    format: "PAPERBACK",
    binding: "Copertina Flessibile",
    is_library: true,
    return_date: null
  },
  {
    id: "17",
    title: "Il Conte di Montecristo",
    author: "Alexandre Dumas",
    pages: 1248,
    genre: "Avventura",
    cover_url: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80",
    status: "WISHLIST",
    start_date: null,
    end_date: null,
    rating: null,
    review_text: null,
    format: null,
    binding: null,
    is_library: false,
    return_date: null
  },
  {
    id: "18",
    title: "Norwegian Wood",
    author: "Haruki Murakami",
    pages: 380,
    genre: "Narrativa",
    cover_url: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=600&q=80",
    status: "OWNED",
    start_date: "2026-08-01",
    end_date: null,
    rating: null,
    review_text: "",
    format: "PAPERBACK",
    binding: "Copertina Flessibile",
    is_library: false,
    return_date: null
  },
  {
    id: "19",
    title: "L'Arte della Guerra",
    author: "Sun Tzu",
    pages: 128,
    genre: "Filosofia",
    cover_url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    status: "READ",
    start_date: "2026-02-01",
    end_date: "2026-02-03",
    rating: 3,
    review_text: "Interessante per il contesto storico e strategico.",
    format: "KINDLE",
    binding: "Digitale",
    is_library: false,
    return_date: null
  },
  {
    id: "20",
    title: "Hyperion",
    author: "Dan Simmons",
    pages: 482,
    genre: "Fantascienza",
    cover_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    status: "WISHLIST",
    start_date: null,
    end_date: null,
    rating: null,
    review_text: null,
    format: null,
    binding: null,
    is_library: false,
    return_date: null
  },
  {
    id: "21",
    title: "La Svastica sul Sole",
    author: "Philip K. Dick",
    pages: 256,
    genre: "Ucronia",
    cover_url: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=600&q=80",
    status: "READ",
    start_date: "2026-06-10",
    end_date: "2026-06-18",
    rating: 4,
    review_text: "Un'ambientazione distopica affascinante e inquietante. Finale aperto molto riflessivo.",
    format: "PAPERBACK",
    binding: "Copertina Flessibile",
    is_library: false,
    return_date: null
  },
  {
    id: "22",
    title: "Lo Hobbit",
    author: "J.R.R. Tolkien",
    pages: 310,
    genre: "Fantasy",
    cover_url: "https://images.unsplash.com/photo-1463320726281-696a485928c7?auto=format&fit=crop&w=600&q=80",
    status: "OWNED",
    start_date: "2026-08-15",
    end_date: null,
    rating: null,
    review_text: "",
    format: "HARDCOVER",
    binding: "Copertina Rigida",
    is_library: false,
    return_date: null
  },
  {
    id: "23",
    title: "L'Ombra dello Scorpione",
    author: "Stephen King",
    pages: 1152,
    genre: "Horror / Post-apocalittico",
    cover_url: "https://images.unsplash.com/photo-1509021436468-d510300f28b4?auto=format&fit=crop&w=600&q=80",
    status: "WISHLIST",
    start_date: null,
    end_date: null,
    rating: null,
    review_text: null,
    format: null,
    binding: null,
    is_library: false,
    return_date: null
  },
  {
    id: "24",
    title: "Mendel dei libri",
    author: "Stefan Zweig",
    pages: 64,
    genre: "Narrativa Breve",
    cover_url: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&w=600&q=80",
    status: "READ",
    start_date: "2026-07-01",
    end_date: "2026-07-01",
    rating: 5,
    review_text: "Una perla di rara bellezza. La passione per i libri raccontata in poche indimenticabili pagine.",
    format: "PAPERBACK",
    binding: "Copertina Flessibile",
    is_library: true,
    return_date: null
  },
  {
    id: "25",
    title: "Snow Crash",
    author: "Neal Stephenson",
    pages: 480,
    genre: "Cyberpunk",
    cover_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80",
    status: "OWNED",
    start_date: null,
    end_date: null,
    rating: null,
    review_text: "",
    format: "KINDLE",
    binding: "Digitale",
    is_library: false,
    return_date: null
  },
  {
    id: "26",
    title: "Orgoglio e Pregiudizio",
    author: "Jane Austen",
    pages: 432,
    genre: "Classico",
    cover_url: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80",
    status: "WISHLIST",
    start_date: null,
    end_date: null,
    rating: null,
    review_text: null,
    format: null,
    binding: null,
    is_library: false,
    return_date: null
  },
  {
    id: "27",
    title: "Le Città Invisibili",
    author: "Italo Calvino",
    pages: 160,
    genre: "Narrativa / Filosofico",
    cover_url: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=600&q=80",
    status: "READ",
    start_date: "2026-03-10",
    end_date: "2026-03-15",
    rating: 5,
    review_text: "Poesia pura in prosa. Calvino costruisce mondi fantastici e metafore indimenticabili.",
    format: "PAPERBACK",
    binding: "Copertina Flessibile",
    is_library: false,
    return_date: null
  },
  {
    id: "28",
    title: "L'Alchimista",
    author: "Paulo Coelho",
    pages: 180,
    genre: "Romanzo Filosofico",
    cover_url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=600&q=80",
    status: "OWNED",
    start_date: "2026-08-20",
    end_date: null,
    rating: null,
    review_text: "",
    format: "PAPERBACK",
    binding: "Copertina Flessibile",
    is_library: true,
    return_date: "2026-09-20"
  },
  {
    id: "29",
    title: "Solaris",
    author: "Stanisław Lem",
    pages: 220,
    genre: "Fantascienza",
    cover_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    status: "WISHLIST",
    start_date: null,
    end_date: null,
    rating: null,
    review_text: null,
    format: null,
    binding: null,
    is_library: false,
    return_date: null
  },
  {
    id: "30",
    title: "Il Ritratto di Dorian Gray",
    author: "Oscar Wilde",
    pages: 250,
    genre: "Classico",
    cover_url: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=600&q=80",
    status: "READ",
    start_date: "2026-01-15",
    end_date: "2026-01-22",
    rating: 4,
    review_text: "Aforismi geniali e una profonda indagine sull'estetismo e la moralità.",
    format: "KINDLE",
    binding: "Digitale",
    is_library: false,
    return_date: null
  }
];